const HAIR = [
  { id: 'hair_1', image: require('../../../assets/hair/hair_1.png') },
  { id: 'hair_2', image: require('../../../assets/hair/hair_2.png') },
  { id: 'hair_3', image: require('../../../assets/hair/hair_3.png') },
  { id: 'hair_4', image: require('../../../assets/hair/hair_4.png') },
  { id: 'hair_5', image: require('../../../assets/hair/hair_5.png') },
  { id: 'hair_6', image: require('../../../assets/hair/hair_6.png') },
  { id: 'hair_7', image: require('../../../assets/hair/hair_7.png') },
  { id: 'hair_8', image: require('../../../assets/hair/hair_8.png') },
  { id: 'hair_9', image: require('../../../assets/hair/hair_9.png') },
  { id: 'hair_10', image: require('../../../assets/hair/hair_10.png') },
  { id: 'hair_11', image: require('../../../assets/hair/hair_11.png') },
  { id: 'hair_12', image: require('../../../assets/hair/hair_12.png') },
  { id: 'hair_13', image: require('../../../assets/hair/hair_13.png') },
  { id: 'hair_14', image: require('../../../assets/hair/hair_14.png') },
  { id: 'hair_15', image: require('../../../assets/hair/hair_15.png') },
  { id: 'hair_16', image: require('../../../assets/hair/hair_16.png') },
  { id: 'hair_17', image: require('../../../assets/hair/hair_17.png') },
  { id: 'hair_18', image: require('../../../assets/hair/hair_18.png') },
  { id: 'hair_19', image: require('../../../assets/hair/hair_19.png') },
  { id: 'hair_20', image: require('../../../assets/hair/hair_20.png') },
  { id: 'hair_21', image: require('../../../assets/hair/hair_21.png') },
  { id: 'hair_22', image: require('../../../assets/hair/hair_22.png') },
  { id: 'hair_23', image: require('../../../assets/hair/hair_23.png') },
  { id: 'hair_24', image: require('../../../assets/hair/hair_24.png') },
  { id: 'hair_25', image: require('../../../assets/hair/hair_25.png') },
  { id: 'hair_26', image: require('../../../assets/hair/hair_26.png') },
  { id: 'hair_27', image: require('../../../assets/hair/hair_27.png') },
  { id: 'hair_28', image: require('../../../assets/hair/hair_28.png') },
  { id: 'hair_29', image: require('../../../assets/hair/hair_29.png') },
  { id: 'hair_30', image: require('../../../assets/hair/hair_30.png') },
  { id: 'hair_31', image: require('../../../assets/hair/hair_31.png') },
  { id: 'hair_32', image: require('../../../assets/hair/hair_32.png') },
  { id: 'hair_33', image: require('../../../assets/hair/hair_33.png') },
];

export default HAIR;